### ISSUE TITLE
Animal Skins/Hides

### ISSUE THREAD

**Issue by DianaWinters** [RWA-Team/RimworldAscension#102]
butchering a creature should yield 1 [(Animal Age)(Animal Name)] Skin that needs to be treated to be turned into [Animal Name] Hide/Leather

ex.
Butchering a juvenile Muffalo would yield 1 juvenile Muffalo skin, which would then be treated into the appropriate amount of Hide/Leather

**Comment by DianaWinters** [comment]
Note: small creature skins should yield leather strips

**Comment by Wivex** [comment]
We won't do animal hide into leather processing. However, we will make some "furry" creatures yield wool or fur when butchered. And leather could be processed into leather strips in neolithic.
