### ISSUE TITLE
Neolithic leather armor set

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#111]
made from hardened leather (leather hardened in kiln)
it's should look thick and "protective", but without any metal parts (could be stiches there instead, or just nothing). And white "stuff based", ofc:
![image](https://cloud.githubusercontent.com/assets/13631287/16270805/4d345efa-38a0-11e6-90de-d62fd5ad52f0.png)

**Comment by DianaWinters** [comment]
https://www.youtube.com/watch?v=tXcGXTtsgmE

**Comment by Wivex** [comment]
it's not meant to be equal to metal armor types. But still be better than just leather clothing. Protect your hunters from wild animals and stuff liek that.

**Comment by DianaWinters** [comment]
> Protect your hunters from wild animals and stuff liek that.

Bear armor: http://i.imgur.com/f7m4Ni2.jpg

**Comment by Wivex** [comment]
![image](https://cloud.githubusercontent.com/assets/13631287/16552395/71794190-41c9-11e6-9dd8-76644bef6de7.png)

**Comment by Wivex** [comment]
![armorleather](https://cloud.githubusercontent.com/assets/13631287/18477009/dd8f314e-79d4-11e6-8bd0-eb4506c3639a.png)
![armorleather_fat_back](https://cloud.githubusercontent.com/assets/13631287/18477010/dd8f7082-79d4-11e6-88d7-091b248c8f39.png)
![armorleather_fat_front](https://cloud.githubusercontent.com/assets/13631287/18477017/ddaffc30-79d4-11e6-9ca6-b649de65574d.png)
![armorleather_fat_side](https://cloud.githubusercontent.com/assets/13631287/18477013/dd994422-79d4-11e6-8bda-522c869cef18.png)
![armorleather_female_back](https://cloud.githubusercontent.com/assets/13631287/18477011/dd909fe8-79d4-11e6-9f90-d303b0140802.png)
![armorleather_female_front](https://cloud.githubusercontent.com/assets/13631287/18477012/dd9154d8-79d4-11e6-9887-15712c03321e.png)
![armorleather_female_side](https://cloud.githubusercontent.com/assets/13631287/18477014/ddade184-79d4-11e6-9e6f-437390b2d442.png)
![armorleather_hulk_back](https://cloud.githubusercontent.com/assets/13631287/18477016/ddaf503c-79d4-11e6-9327-c1b3166baad1.png)
![armorleather_hulk_front](https://cloud.githubusercontent.com/assets/13631287/18477015/ddae15e6-79d4-11e6-8bdd-b6e0406eaebd.png)
![armorleather_hulk_side](https://cloud.githubusercontent.com/assets/13631287/18477018/ddb67b82-79d4-11e6-8c37-4975903f16fe.png)
![armorleather_male_back](https://cloud.githubusercontent.com/assets/13631287/18477019/ddb7c460-79d4-11e6-9bff-8d61c3ee1e7f.png)
![armorleather_male_front](https://cloud.githubusercontent.com/assets/13631287/18477020/ddcb9738-79d4-11e6-9c64-b907adebc133.png)
![armorleather_male_side](https://cloud.githubusercontent.com/assets/13631287/18477021/ddcbd00e-79d4-11e6-84cf-16614ee5ac20.png)
![armorleather_thin_back](https://cloud.githubusercontent.com/assets/13631287/18477022/ddce1c06-79d4-11e6-9a56-9e98d580196f.png)
![armorleather_thin_front](https://cloud.githubusercontent.com/assets/13631287/18477023/ddd24f9c-79d4-11e6-877b-bf92f982769b.png)
![armorleather_thin_side](https://cloud.githubusercontent.com/assets/13631287/18477024/ddd414a8-79d4-11e6-8451-8579beb6721b.png)
