### ISSUE TITLE
Add comp for all weapons to draw pawn "hand" on it, when equipped

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#113]
hand is drawn as overlay over weapon, position shift is set in def.
PawnRenderer

![image](https://cloud.githubusercontent.com/assets/13631287/16358953/f0c32960-3b2b-11e6-8c51-9bd0b03174a2.png)

**Comment by Ristellise** [comment]
looks nice :stuck_out_tongue:

**Comment by Tapkevich** [comment]
I want this to be some kind of boss in neolithic era its just too epic :D

**Comment by Wivex** [comment]
"A wild mrofa appears. Quickly, make him texture requests, before he chops all your colonists."

**Comment by Ristellise** [comment]
> "A wild mrofa appears. Quickly, make him texture requests, before he chops all your colonists."

Easteregg pls :P
