### ISSUE TITLE
Make masks for all those weapons

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#162]
mask to separate stuff parts from non stuff:
![sling](https://cloud.githubusercontent.com/assets/13631287/17208784/c37767f4-54c2-11e6-9c58-f769a8d6abaa.png)
![handaxeneolithic](https://cloud.githubusercontent.com/assets/13631287/17208793/c95f3836-54c2-11e6-9d44-909a4e6adbcd.png)
![hammerneolithic](https://cloud.githubusercontent.com/assets/13631287/17208797/ca59742c-54c2-11e6-8150-f3da6fc9ada8.png)
![axe](https://cloud.githubusercontent.com/assets/13631287/17208826/da413c58-54c2-11e6-9eca-4f98497f0c58.png)
![dagger](https://cloud.githubusercontent.com/assets/13631287/17208823/da409dac-54c2-11e6-9725-420d2b7cedaf.png)
![hammer](https://cloud.githubusercontent.com/assets/13631287/17208825/da410f30-54c2-11e6-848e-850f49e2e36f.png)
![pickaxe](https://cloud.githubusercontent.com/assets/13631287/17208824/da410788-54c2-11e6-9666-2b3fadbc78c0.png)

**Comment by mrofa** [comment]
![medivalgladius_m](https://cloud.githubusercontent.com/assets/10467365/17217889/43ee62ac-54e6-11e6-8f2e-21a3cdbc0b38.png)
![medivalgladius](https://cloud.githubusercontent.com/assets/10467365/17217896/46a5cbc0-54e6-11e6-86c4-34aa43334b30.png)
![medivalaxe_m](https://cloud.githubusercontent.com/assets/10467365/17217900/4985e94c-54e6-11e6-8f6f-20e42928a02c.png)
![medivalaxe](https://cloud.githubusercontent.com/assets/10467365/17217902/4aea6920-54e6-11e6-89f2-1eb23f834f6e.png)
![tribalhammer_m](https://cloud.githubusercontent.com/assets/10467365/17217909/4ec1195e-54e6-11e6-83a2-d60a4930ec8a.png)
![tribalhammer](https://cloud.githubusercontent.com/assets/10467365/17217915/508a01ba-54e6-11e6-82ff-2bda663bbf1f.png)
![tribalaxe](https://cloud.githubusercontent.com/assets/10467365/17217917/51db85ac-54e6-11e6-9b9e-d63979d665ef.png)
![tribalaxe_m](https://cloud.githubusercontent.com/assets/10467365/17217919/531c6a76-54e6-11e6-8890-5414b09efde6.png)

**Comment by mrofa** [comment]
![medivalhammer](https://cloud.githubusercontent.com/assets/10467365/17223345/6e2fab1e-54fc-11e6-8f52-4ac5eb6cd7d3.png)
![medivalhammer_m](https://cloud.githubusercontent.com/assets/10467365/17223347/6f9ef766-54fc-11e6-9f18-24571fc7be72.png)

**Comment by Wivex** [comment]
The hammer is really good. Much better than original.
