### ISSUE TITLE
Graphic bug with palisade contact with another wall / natural rock wall

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#19]

**Comment by DianaWinters** [comment]
palisades also don't snap properly to doors

**Comment by DianaWinters** [comment]
side note
![palisade_atlas](https://cloud.githubusercontent.com/assets/19817534/16079250/2ea6825c-32c8-11e6-9353-1c3347cd2920.png)
updated atlas

**Comment by Wivex** [comment]
i was bothering shinzy about this atlas for so long. Thx for the fix

**Comment by DianaWinters** [comment]
tell Shinzy to never have me do things for him again
