### ISSUE TITLE
HUD is gone after blueprints or beds are placed

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#23]
The game looks like it crashes but sends out no crash log.
The game freezes, and the HUD disappears. No crash log.

EDIT: I'll try to do a full reinstall
EDIT x2: It has seemed to fix the game freezing, but the HUD still disappears. I can still pan the camera around but I have no control of game speed or selections

**Comment by Wivex** [comment]
"This happened to me when i put down my first building blueprint"

**Comment by Ristellise** [comment]
why?

**Comment by Wivex** [comment]
i have no idea. It was reply from forum. But to know what causes it i need to know excactly how that happens. When i try to do the same, it works fine for me, without any problems.

**Comment by Wivex** [comment]
fixed
