### ISSUE TITLE
Clay clump\ Sand pile

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#33]
Some kind of formless clump for clay resource. I currently use this as a place holder

![clumpclay](https://cloud.githubusercontent.com/assets/13631287/15533968/784e28a6-226f-11e6-84e9-6db850203ed3.png)

but it's too plain and and could be adjusted or redrawn to have a proper clump shape and curves.

**Comment by Wivex** [comment]
![clump](https://cloud.githubusercontent.com/assets/13631287/15648115/0e967048-2671-11e6-95e2-79dd388878b5.png)

**Comment by Wivex** [comment]
![console_addon 5](https://cloud.githubusercontent.com/assets/13631287/15806412/6dc1133c-2b4b-11e6-869f-d432a6b4ba76.png)

**Comment by Ristellise** [comment]
ehh.. would have liked the previous one...

**Comment by Wivex** [comment]
![mask](https://cloud.githubusercontent.com/assets/13631287/15856947/516e9e30-2cc1-11e6-9a09-534c6123f95b.png)
![console_addon 2](https://cloud.githubusercontent.com/assets/13631287/15856948/518529c0-2cc1-11e6-8f05-50f2958e18aa.png)
![console_addon 1](https://cloud.githubusercontent.com/assets/13631287/15856810/ae761e24-2cc0-11e6-958f-db17af32ec2b.png)
