### ISSUE TITLE
Animal sleeping box

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#34]
Vanilla sleeping box make no sence, so i want you to make an analof og it using the hay bed texture. It will be basically the same hay bed, but square one for animals (i would make it without wood base, just as a hay spot)

**Comment by Ristellise** [comment]
Looks easy to do... just place hay texture over the box.

**Comment by Wivex** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/13631287/15649668/f0f470a2-267b-11e6-999b-fac9ac79bfe9.png)
