### ISSUE TITLE
Some items missing from ThingFilter list.

### ISSUE THREAD

**Issue by campaignupgrade** [RWA-Team/RimworldAscension#43]
Medicine can't be hauled. 

I know this is a known issue. I'm only including it for completeness.

**Comment by Wivex** [comment]
Vanilla items are not connected to the new ThingCategory system. So ThingFilter system doesn't work well yet. This requires redefining defs of vanilla items we gonna use with proper Thingcategory tag values.

**Comment by Wivex** [comment]
Considered fixed, since all defs are going to be rechecked.
