### ISSUE TITLE
Tool usage reservation bug

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#48]
pawn don't reswap weapon/tool they just drop it and never pick the other, so i have to manually tell them to retake they're weapon (temp fix is to have fighter not do a thing that need tool, but it lower the amount of worker)

**Comment by campaignupgrade** [comment]
The temp fix might be a feature not a bug. 

One of the defining features of the neolithic era was the first true division of labor; for the first time you have distinct, full-time work roles like warrior, farmer, priest, king.

The temp fix means warriors will do nothing but hunt, train, and some jobs that take no tools.

**Comment by Wivex** [comment]
>  pawn don't reswap weapon/tool they just drop it and never pick the other, so i have to manually tell them to retake they're weapon (temp fix is to have fighter not do a thing that need tool, but it lower the amount of worker)
> 
>  —
>  You are receiving this because you are subscribed to this thread.
>  Reply to this email directly, view it on GitHub <#48>, or mute the thread https://github.com/notifications/unsubscribe/AEI-hXNCFqhd23neDhYXvycxP4cbbg7Pks5qG8w2gaJpZM4IqMr1.

why is it here?

anyway, i'll change the tool "preserving" mechanic to make pawns keep their tools in their inventory, if you assign them to pawns via float menu (right click on lying tool to assign to pawn).
Otherwise pawns would drop those tools after use.

**Comment by Wivex** [comment]
new tool system should've fixed that
