### ISSUE TITLE
Make cut wood designation icon (which hovers over trees, designated to be cut)

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#56]
Do similar "semi transparent, greenish" axe icon, same as cut/harvest designations icons (the similar angle and size of axe should be set on the texture itself):
![cutplant](https://cloud.githubusercontent.com/assets/13631287/15799266/255dbae2-2a5f-11e6-8c43-bb0085ff9434.png)
![harvestplant](https://cloud.githubusercontent.com/assets/13631287/15799253/b19d73e0-2a5e-11e6-968d-08f7ccb71b48.png)
![harvestwood](https://cloud.githubusercontent.com/assets/13631287/15799252/b19a9a94-2a5e-11e6-98de-aefe778e9920.png)

**Comment by DianaWinters** [comment]
http://i.imgur.com/JfOXREG.png

**Comment by Wivex** [comment]
![axe](https://cloud.githubusercontent.com/assets/13631287/15965228/46fe5baa-2f25-11e6-93c0-c000659b64f3.png)
![image](https://cloud.githubusercontent.com/assets/13631287/15957932/fa7e8a90-2efa-11e6-91d1-cf7ce8052ef0.png)
nice. But you could paste the result image directly in the comment window. It will be uploaded from your buffer.
