### ISSUE TITLE
Replace vanilla slate with obsidian

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#66]
- change map gen to spawn smaller areas of slate, if possible
- make it a "rare" stone subtype, with exceptional sharp damage, beauty and market values, but lower durability

**Comment by DianaWinters** [comment]
Note: Obsidian is rather fragile (like glass) so when used for ammunition/as a weapon, it wouldn't do much damage to armored targets

**Comment by Wivex** [comment]
we gonna have armor penetration stat for our weapons. Could be applied for obsidian

**Comment by DianaWinters** [comment]
the item health modifier should be low as well

**Comment by Wivex** [comment]
def added, vanilla textures used
