### ISSUE TITLE
Colonists won't do anything

### ISSUE THREAD

**Issue by DianaWinters** [RWA-Team/RimworldAscension#69]
After some time, the colonists just stopped doing all non-dumb labor jobs. There was nothing in the dev log indicating an issue. Saving and reloading did not fix this issue.

**Comment by DianaWinters** [comment]
Note: Hunting, Researching, Crafting jobs seem to still work, but equipping a weapon causes errors.
Note2: cutting bushes and harvesting berries still works, but cutting trees doesn't
Note3: the weapon errors only appear on Lumi and Engie (the pawns that I had equip the multitools)
Note4:the multitools are no longer in said colonist's inventory
Note5: Notes 3&4 are invalid-- any colonist with "repair" as an active job will get the error when equipping a weapon

**Comment by Ristellise** [comment]
~ how long does it take to get into this state?

**Comment by DianaWinters** [comment]
about an hour

**Comment by Wivex** [comment]
it's all related to the missing compTool on any of in-game weapons. The whole job system breaks because of that.

**Comment by Wivex** [comment]
def based issue, will be fixed when necessary weapon defs redefined
