### ISSUE TITLE
Cobble road texture

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#70]
![cobble_atlas 1](https://cloud.githubusercontent.com/assets/13631287/15976821/c9d528b4-2f5d-11e6-9b76-39a8bbc6ca9f.png)

**Comment by DianaWinters** [comment]
![cobble_atlas](https://cloud.githubusercontent.com/assets/19817534/15975038/19dbae16-2f11-11e6-8e1e-58d6b32aebc3.png)

**Comment by Wivex** [comment]
![image](https://cloud.githubusercontent.com/assets/13631287/15975143/be82bc50-2f54-11e6-871d-5f74703d5892.png)

nice, now you need to do the rest "uncut" segmements
Or try to add curn to the cut ones first, to check the final result

**Comment by DianaWinters** [comment]
![cobble_atlas](https://cloud.githubusercontent.com/assets/19817534/15975660/1fe15d30-2f14-11e6-8e3a-c816ed6a3719.png)
