### ISSUE TITLE
Medival furnace texture 

### ISSUE THREAD

**Issue by Tapkevich** [RWA-Team/RimworldAscension#74]
It should be 4x1 texture. Furnance consist of :
Coal bunker - 1x1
Instruments and stuff - 1x1
Furnance itself (with fire and stuff) 1x1. 
Bellows 1x1 

Here some refs:
![810846305_bf1cf6058b](https://cloud.githubusercontent.com/assets/15946372/15967938/7ac3bfe0-2f32-11e6-823e-edceb126b574.jpg)
![bf_6](https://cloud.githubusercontent.com/assets/15946372/15967939/7ae213e6-2f32-11e6-9dcd-15f66840182f.jpg)

We cant make it as real one becouse of engine restrictions so everything have to be but in 1 line.

**Comment by Wivex** [comment]
i prefer this concept:
![pasted image at 2016_06_10 17_41](https://cloud.githubusercontent.com/assets/13631287/15968258/dab4a7ba-2f33-11e6-833b-d80d0d98754e.png)

**Comment by DianaWinters** [comment]
![furnacet](https://cloud.githubusercontent.com/assets/19817534/15984433/18fcbaec-2f90-11e6-8d7f-4f71bfbbf272.png)
another concept/reference

**Comment by Wivex** [comment]
i need a combination of this (it should be made whole from cobbles put together, no clay):
![image](https://cloud.githubusercontent.com/assets/13631287/16073946/e4a0b19a-32f0-11e6-89f5-8953e69bb8a1.png)
with my previous concept (some form of slides for the smelted materials. Ingridients will be placed there, while pawn operates in the middle)

**Comment by DianaWinters** [comment]
![pyre](https://cloud.githubusercontent.com/assets/19817534/16112071/570d57a8-337b-11e6-9866-ddc3fc4b9c14.png)

**Comment by Wivex** [comment]
![klint 3](https://cloud.githubusercontent.com/assets/13631287/16358426/150f0868-3b1b-11e6-9df0-9b2ab120c339.png)

**Comment by Wivex** [comment]
![klint 4](https://cloud.githubusercontent.com/assets/13631287/16428293/e94cc948-3d79-11e6-9846-a2748a8f7802.png)

**Comment by Wivex** [comment]
![furnace](https://cloud.githubusercontent.com/assets/13631287/16514897/6a839c86-3f77-11e6-83c6-0fd3c2a9968c.png)
![klint 1](https://cloud.githubusercontent.com/assets/13631287/16514907/7579d006-3f77-11e6-9b33-04af240a7504.png)

**Comment by Ristellise** [comment]
Second one is better.
