### ISSUE TITLE
Medival furnance texture 

### ISSUE THREAD

**Issue by Tapkevich** [RWA-Team/RimworldAscension#75]
It should be 4x1 texture. Furnance consist of :
Coal bunker - 1x1
Instruments and stuff - 1x1
Furnance itself (with fire and stuff) 1x1. 
Bellows 1x1 

Here some refs:
![810846305_bf1cf6058b](https://cloud.githubusercontent.com/assets/15946372/15967938/7ac3bfe0-2f32-11e6-823e-edceb126b574.jpg)
![bf_6](https://cloud.githubusercontent.com/assets/15946372/15967939/7ae213e6-2f32-11e6-9dcd-15f66840182f.jpg)

We cant make it as real one becouse of engine restrictions so everything have to be but in 1 line.

**Comment by Ristellise** [comment]
duplicate.
