### ISSUE TITLE
Suggestion Box (Throw all SUGGESTING HERE)

### ISSUE THREAD

**Issue by Ristellise** [RWA-Team/RimworldAscension#76]
left blank for a reason untill people start throwing it in.

**Comment by Joshwoo70** [comment]
Add Whiskey, Vodka, and Sake to Fermentation

Exotic Cultivation (Medieval)
   - Unlocks growing Agave, Bananas, Oranges, Grapes, etc...
   - Unlocks brewing Tequila and Wine if fermentation has already been researched

Soil Cultivation (Neolithic?)
   - Unlocks the ability to plow soil to improve growth speed
   - Allows you to place soil on stone floors that have been smoothed

Permafrost (Neolithic?)
   - Allows you to dig up ice (hard work) to access to soil with a similar growth speed to gravel

Fertilizer (Requires Soil Cultivation) (Medieval)
   - Corpses can be turned into fertilizer, which can be used to make very fertile soil that can be placed on permafrost, soil, or smooth stone

Cooking I (Medieval?)
   - Unlocks more sophisticated methods of cooking
   - Allows for production of soy milk out of beans (OP?)
   - Chocolate from cocoa beans, Tea from tea leaves, and coffee from coffee beans

Cooking II (Modern)
   - Electronic cookware
   - icecream
   - Soda

Hospitality I (Medieval?)
   - Allows production of (non chemical) mood boosting items, as well as certain accommodations for visitors/traders
   - Ex. Orange Julius (Oranges, Sugar, Milk)
           Guest Beds
            Negotiators can increase relations
            Chess Boards

Hospitality II (Modern?)
   - More joy items (pool table)
   - Ability to have negotiators recruit visitors
Originally from here by DianaWinters:
https://github.com/RWA-Team/RimworldAscension/issues/72

**Comment by DianaWinters** [comment]
https://www.youtube.com/watch?v=2C6_pSEPbO8

more neolithic weapon ideas

**Comment by Wivex** [comment]
each issue should refer to one problem, ideally. Or one suggestion.

**Comment by Ristellise** [comment]
sure then. locking this page
