### ISSUE TITLE
Medieval Apparel

### ISSUE THREAD

**Issue by DianaWinters** [RWA-Team/RimworldAscension#78]
Gambesons - Linen/Wool armor (stuffed w/ cloth)
Jack chains - Cheap alternative to platemail http://s1107.photobucket.com/user/woodsarmoury/media/Jack-Chains-MK2-07.jpg.html

Note: the areas hit in combat should be revised. You're not likely to cut off toes in a swordfight. You are likely to hit the arms if fighting a competent opponent

**Comment by Wivex** [comment]
once i'll do the CR implementation (probably by the end of June), it will rely on Tap as balancing issue.

**Comment by DianaWinters** [comment]
Further - Collecting silk from (giant?)spiders, perhaps tameable ones
silk could be used to make luxury clothing that can be worn or sold for a decent price

**Comment by Wivex** [comment]
> Further - Collecting silk from (giant?)spiders, perhaps tameable ones
> silk could be used to make luxury clothing that can be worn or sold for a decent price

 one is really good
