### ISSUE TITLE
Preservation

### ISSUE THREAD

**Issue by DianaWinters** [RWA-Team/RimworldAscension#85]
http://nchfp.uga.edu/publications/nchfp/factsheets/food_pres_hist.html

Pick and choose which methods would be appropriate for each era

**Comment by Wivex** [comment]
Drying for neolithic, freezing since modern. Could suggest smth to choose for medieval.

**Comment by DianaWinters** [comment]
perhaps snow can be collected and placed. it lowers the temperature of the room it's placed in (it will melt of course)

also, fermentation was important for the medieval age, but salting meats and smoking fish could work
jams and jelly would also work

**Comment by Wivex** [comment]
Fueled smoker will be used for medieval preservation
