### ISSUE TITLE
Jewelry textures

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#91]
![ring_m 1](https://cloud.githubusercontent.com/assets/13631287/16073442/8e5a6468-32ee-11e6-9be4-8d9fbed19cbf.png)
![ring_m](https://cloud.githubusercontent.com/assets/13631287/16073443/8e5df376-32ee-11e6-83f3-09f9adba0213.png)

**Comment by DianaWinters** [comment]
anything else?

**Comment by Wivex** [comment]
no
![ring_m](https://cloud.githubusercontent.com/assets/13631287/16074747/a5c6cff0-32f4-11e6-953f-9308b131b618.png)

![pasted image at 2016_06_15 12_05](https://cloud.githubusercontent.com/assets/13631287/16074728/8d4503de-32f4-11e6-9a5c-246fa595832e.png)
![ring_c_m](https://cloud.githubusercontent.com/assets/13631287/16074729/8d472984-32f4-11e6-86e2-ca47fd4a60be.png)
![ring_sa_m](https://cloud.githubusercontent.com/assets/13631287/16074731/8d492e64-32f4-11e6-8ee0-ce504807c095.png)
![ring_j_m 1](https://cloud.githubusercontent.com/assets/13631287/16074730/8d485cc8-32f4-11e6-9891-81728547778d.png)
