### ISSUE TITLE
Designations icons

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#92]
i need additional designation icon (same as for wood chop) for the mining, plowing (cultivating) and collecting.
Mining icon should be a small pickaxe, smth like this:
![image](https://cloud.githubusercontent.com/assets/13631287/16075974/dcacafda-32f9-11e6-8be6-d5a4bcb3068a.png)

Plowing icon should be a small shovel, smth like this:
![image](https://cloud.githubusercontent.com/assets/13631287/16075992/f2cfd92c-32f9-11e6-9d74-a001834f7add.png)

Collecting:
![feedbackequip tex](https://cloud.githubusercontent.com/assets/13631287/16076224/ed1901ba-32fa-11e6-938e-7a8896653128.png)

All icons should be the same vanilla style
![chopwood](https://cloud.githubusercontent.com/assets/13631287/16076008/037536aa-32fa-11e6-8f65-45be04098703.png)

**Comment by DianaWinters** [comment]
you plow with a hoe, not a shovel

**Comment by Ristellise** [comment]
![hoe](https://cloud.githubusercontent.com/assets/7894419/16076934/67fea330-3328-11e6-93de-99ccab8b1bc4.jpg)
Hoe a test sheet.

**Comment by Ristellise** [comment]
![hoe](https://cloud.githubusercontent.com/assets/7894419/16077097/542871aa-3329-11e6-9656-c9f50a936534.jpg)
Hoe MK2 more smooth.

**Comment by DianaWinters** [comment]
![collecting](https://cloud.githubusercontent.com/assets/19817534/16077283/849865be-32bd-11e6-9aa4-91683e6cdb0d.png)

**Comment by DianaWinters** [comment]
![mining](https://cloud.githubusercontent.com/assets/19817534/16077602/87264736-32bf-11e6-945a-3151ce0d1e4f.png)

**Comment by Wivex** [comment]
make pick icon flipped with pointy side downwards and make it solid color, like axe designation icon

**Comment by DianaWinters** [comment]
![mining](https://cloud.githubusercontent.com/assets/19817534/16079942/af528f74-32cb-11e6-90e3-c926b39bcb72.png)

**Comment by DianaWinters** [comment]
![plow](https://cloud.githubusercontent.com/assets/19817534/16081501/43b7c8bc-32d3-11e6-86ed-a7c0a4aa133b.png)

**Comment by Wivex** [comment]
good, thx
