### ISSUE TITLE
New Burial mechanic

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#93]
Neolithic burial is based on cremation in pyre (need bed-like texture with pawn drawn on top) (require wood + corpse). Negates/decreases mood penalty for loss.
Medieval burial is based on burial in vanilla grave (require shovel to dig out). Need shovel texture (wood + metal) for that.

**Comment by DianaWinters** [comment]
![shovel](https://cloud.githubusercontent.com/assets/19817534/16103685/27b328d8-3340-11e6-8d13-d350221b5fce.png)

**Comment by DianaWinters** [comment]
![pyre](https://cloud.githubusercontent.com/assets/19817534/16104232/fcea5f40-3344-11e6-8acc-c81e1ae34269.png)
It wouldn't make much sense for a corpse that wasn't the one being burnt being on it :/

**Comment by Wivex** [comment]
i meant that pire will work like bed, if you place corpse there, it's drawn above.

Shovel needs notch here, to look right. Also, i need it's metal parts stuffed (white, and with mask)
![image](https://cloud.githubusercontent.com/assets/13631287/16107818/7659ebea-33a7-11e6-933d-cc74a2db21c8.png)

Pyre need to bed single bed size (2x1), with "depth", not just flat texture. Could use log wall texture for the "base":
![walllog_atlas](https://cloud.githubusercontent.com/assets/13631287/16108693/5d7f862e-33ad-11e6-9f46-1058fbc2b157.png)

**Comment by DianaWinters** [comment]
![shovel](https://cloud.githubusercontent.com/assets/19817534/16108768/d4b001bc-336a-11e6-8e4d-f0e8fd35bb39.png)

**Comment by DianaWinters** [comment]
![pyre](https://cloud.githubusercontent.com/assets/19817534/16108799/fcb9ac94-336a-11e6-9a72-ac52dafcbe44.png)
not sure how to add more depth

**Comment by Wivex** [comment]
add log wall sides on the side of the pyre

**Comment by DianaWinters** [comment]
![pyre](https://cloud.githubusercontent.com/assets/19817534/16109356/f650aa8a-336d-11e6-9509-ff265afb1b37.png)

**Comment by DianaWinters** [comment]
that'd make it hard to distinguish the two

**Comment by Wivex** [comment]
If made properly, and with the same color tone, it would be ok. The sides should be smaller than i did, but it looks much more like actual pyre:
![image](https://cloud.githubusercontent.com/assets/13631287/16109712/ddece252-33b2-11e6-82e2-53d713cf3ec8.png)

**Comment by DianaWinters** [comment]
it looks like throwing them in a pit

**Comment by Wivex** [comment]
cause i made the to part too small. You need to add much smaller scaled sides

**Comment by DianaWinters** [comment]
![pyre](https://cloud.githubusercontent.com/assets/19817534/16112085/6372b8c6-337b-11e6-9b08-16dd01809354.png)

**Comment by DianaWinters** [comment]
![pyres](https://cloud.githubusercontent.com/assets/19817534/16114924/987867e2-3389-11e6-91f0-3d1e7a8d1c73.png)

**Comment by Wivex** [comment]
the bottom of the last texture looks really strange, aligned sideways. Fix it please.

**Comment by DianaWinters** [comment]
![pyres 1](https://cloud.githubusercontent.com/assets/19817534/16116626/a38b1bb6-3393-11e6-9d91-93efb3db8ac2.png)

**Comment by Wivex** [comment]
hmm, i didn't meant what you did, but it actually doesn't matter anymore. It should be fine in small scale on map.

Still need mask for shovel.

**Comment by DianaWinters** [comment]
![shovel_m](https://cloud.githubusercontent.com/assets/19817534/16118171/7ba3c0f0-339b-11e6-8b62-0b8cb3dd61bc.png)

**Comment by DianaWinters** [comment]
![shovel_m](https://cloud.githubusercontent.com/assets/19817534/16118248/c8514cce-339b-11e6-8f02-21bf6ac46d82.png)

**Comment by DianaWinters** [comment]
![shovel_m](https://cloud.githubusercontent.com/assets/19817534/16118393/7fde2eca-339c-11e6-934c-e5e9b1c88f0a.png)

**Comment by Wivex** [comment]
Nice, thx.
