### ISSUE TITLE
Various texture requests

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#94]
I need proper textures from those marked sprites (remove white background too). Metal parts of spear and sword should be stuff based (white and with masking texture made), "grains" or those ore types should be stuff based too:
![image](https://cloud.githubusercontent.com/assets/13631287/16089803/7b13f850-3335-11e6-827d-12d8c5b376de.png)

![image](https://cloud.githubusercontent.com/assets/13631287/16089820/897ab320-3335-11e6-9825-1f9eb26b34a5.png)

**Comment by DianaWinters** [comment]
![ore1_m](https://cloud.githubusercontent.com/assets/19817534/16103553/2a7c7f7a-333f-11e6-9c22-8b1fb7533888.png)
![ore2](https://cloud.githubusercontent.com/assets/19817534/16103549/2a7a455c-333f-11e6-9f0a-29a80b187485.png)
![ore2_m](https://cloud.githubusercontent.com/assets/19817534/16103550/2a7aa66e-333f-11e6-892e-285b50ce7374.png)
![spear](https://cloud.githubusercontent.com/assets/19817534/16103554/2a7e57e6-333f-11e6-91e1-ca7d88039321.png)
![spear_m](https://cloud.githubusercontent.com/assets/19817534/16103551/2a7ab3de-333f-11e6-8126-4a92ae5df322.png)
![sword](https://cloud.githubusercontent.com/assets/19817534/16103552/2a7b6e46-333f-11e6-9448-547f80f50add.png)
![sword_m](https://cloud.githubusercontent.com/assets/19817534/16103556/2a877eb6-333f-11e6-85a3-e9be81cf2d7d.png)
![club](https://cloud.githubusercontent.com/assets/19817534/16103555/2a873f0a-333f-11e6-99cf-17b1f2b91842.png)
![club_m](https://cloud.githubusercontent.com/assets/19817534/16103557/2a888da6-333f-11e6-94fd-3459ca220c59.png)
![ore1](https://cloud.githubusercontent.com/assets/19817534/16103558/2a8a1aa4-333f-11e6-82c3-73c080058c4a.png)

**Comment by Wivex** [comment]
Nice, thx. But i need grains on the colored ores "white stuffless", so i can add various stuff color to it

**Comment by DianaWinters** [comment]
![ore1](https://cloud.githubusercontent.com/assets/19817534/16107419/de9fc788-3361-11e6-955a-888fae416759.png)
![ore2](https://cloud.githubusercontent.com/assets/19817534/16107420/dead21d0-3361-11e6-8235-317de8428abf.png)
