### ISSUE TITLE
Textures overhaul

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#95]
Add "depth" to those benches:

![tablecarpenter](https://cloud.githubusercontent.com/assets/13631287/16118385/8a450c7e-33df-11e6-9c06-cb65dbf3f920.png)
![tabletailormedieval](https://cloud.githubusercontent.com/assets/13631287/16118400/92f69f5e-33df-11e6-9dea-adf026203f5a.png)
![tablestonecutter](https://cloud.githubusercontent.com/assets/13631287/16125585/f40bb172-33fc-11e6-9fdf-5d239305e6ba.png)
![tablebutchermedieval](https://cloud.githubusercontent.com/assets/13631287/16118420/ac9e6bbc-33df-11e6-89d2-c23fdd12d7f5.png)
![tablebrewermedieval](https://cloud.githubusercontent.com/assets/13631287/16118461/d13fb64c-33df-11e6-97e4-05b77da75453.png)

Shorten the saw, make it 1x1 bench:

![sawmill](https://cloud.githubusercontent.com/assets/13631287/16118502/0a41fa40-33e0-11e6-8a00-8f1a92e44842.png)

**Comment by DianaWinters** [comment]
![image](https://cloud.githubusercontent.com/assets/13631287/16203897/26053fc4-3725-11e6-82bf-a1d928771cad.png)

**Comment by DianaWinters** [comment]
![butcher table](https://cloud.githubusercontent.com/assets/19817534/16138179/834180a8-3400-11e6-9c89-61372defb4a8.png)

**Comment by DianaWinters** [comment]
![carpentry table](https://cloud.githubusercontent.com/assets/19817534/16138421/77fe3bc0-3403-11e6-84a8-8eaa6c382eb8.png)

**Comment by DianaWinters** [comment]
![tailoring station](https://cloud.githubusercontent.com/assets/19817534/16138474/b755c338-3403-11e6-92d6-83f913ad52e1.png)

**Comment by DianaWinters** [comment]
![stonecutting station](https://cloud.githubusercontent.com/assets/19817534/16138508/f5a546d6-3403-11e6-8115-208472d2d0f1.png)

**Comment by DianaWinters** [comment]
![brewery](https://cloud.githubusercontent.com/assets/19817534/16138527/2797ecac-3404-11e6-83d6-e120c89bd9aa.png)

**Comment by Ristellise** [comment]
looks nice! :+1: i approve.

**Comment by Joshwoo70** [comment]
issues closed as request met.

**Comment by Wivex** [comment]
1. textures should not be compressed like that. It's fine if they becom bigger on z axis.
2. i need 3 projection for each table view, like this (also, don't draw black outline where table "top" ends, before going "down"):
   ![tablemachining_back](https://cloud.githubusercontent.com/assets/13631287/16173034/fe611124-359d-11e6-93d3-e811e38d24d3.png)
   ![tablemachining_front](https://cloud.githubusercontent.com/assets/13631287/16173033/fe60fdc4-359d-11e6-99e4-40781a9ed0ea.png)
   ![tablemachining_side](https://cloud.githubusercontent.com/assets/13631287/16173035/fe6411b2-359d-11e6-945a-d38efcd11830.png)
3. Saw blade should be turned the other way. The original texture is wrong too. (-_-)

**Comment by DianaWinters** [comment]
I wish you would have told me that before hand >_>
All you said was to "add depth"

**Comment by Wivex** [comment]
My bad. But that's what it actually meant.

**Comment by DianaWinters** [comment]
![brewery](https://cloud.githubusercontent.com/assets/19817534/16202863/2fd7cbb8-36dd-11e6-885b-1b8919e81fb7.png)
![butcher table](https://cloud.githubusercontent.com/assets/19817534/16202864/2fdc04d0-36dd-11e6-951e-97421cc91ffd.png)
![carpentry table](https://cloud.githubusercontent.com/assets/19817534/16202865/2fe7635c-36dd-11e6-9507-66586e558cab.png)
![saw](https://cloud.githubusercontent.com/assets/19817534/16202867/2ff09dfa-36dd-11e6-8e4e-f3f732cc174a.png)
![stonecutting station](https://cloud.githubusercontent.com/assets/19817534/16202868/2ff135da-36dd-11e6-8c9e-1b9ba1b739fd.png)
![tailoring station](https://cloud.githubusercontent.com/assets/19817534/16202866/2fee04be-36dd-11e6-941a-5bd584b38167.png)

**Comment by Ristellise** [comment]
forget diana would be intrested too :stuck_out_tongue:

**Comment by Wivex** [comment]
can do without it for now
