### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by Tapk0vich** [RWA-Team/RimworldAscension#96]

**Comment by Wivex** [comment]
![image](https://cloud.githubusercontent.com/assets/13631287/16128724/92c37e82-340a-11e6-8332-ae958e74c5a0.png)

**Comment by Tapk0vich** [comment]
Its for advertesting company!

**Comment by Joshwoo70** [comment]
wat.

**Comment by Ristellise** [comment]
locked conversation.

**Comment by Wivex** [comment]
locking doesn't work for team members

**Comment by Ristellise** [comment]
should work.. but why comment on this again?
shrug
