### ISSUE TITLE
Bug with crafting loincloth

### ISSUE THREAD

**Issue by Tapk0vich** [RWA-Team/RimworldAscension#97]
![2016-06-17_18-22-11](https://cloud.githubusercontent.com/assets/19593404/16155569/aaf716ae-34b8-11e6-964c-49e7768cfa36.png)
When i tired to craft loincloth got craft uknown recipe bug in UI.

**Comment by Wivex** [comment]
this is temporary update, not all defs are there yet (i shouldn't have done it half way ready, actually)
